steps:
  - name: ":eslint: Lint"
    command: "npm run lint"
    agents:
      queue: default
    plugins:
      - docker-compose#v3.7.0:
          run: app

  - wait

  - name: ":jest: Test"
    command: "npm run test"
    agents:
      queue: default
