steps:
  - name: "nvm"
    command: "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash"

  - wait  

  - name: ":eslint: Lint"
    command: "script/test.sh"
    agents:
      queue: default

  - wait

  - name: ":jest: Test"
    command: "npm run test"
    agents:
      queue: default
